### ISSUE TITLE
Mixup in grammar singular/plural conversion

### ISSUE THREAD

**Issue by DWhettam** [So-Cool/prolexa#2]
In prolexa_grammar.pl there is a plural->singular conversion for nouns and verbs, however, the function naming implies the opposite. 
```
noun_s2p(Noun_s,Noun_p):-
	( Noun_s=woman -> Noun_p=women
	; Noun_s=man -> Noun_p=men
	; atom_concat(Noun_s,s,Noun_p)
	).

verb_p2s(Verb_p,Verb_s):-
	( Verb_p=fly -> Verb_s=flies
	; 	atom_concat(Verb_p,s,Verb_s)
	).
```
I believe both functions are converting from plural to singular, but noun_s2p implies the opposite

**Comment by So-Cool** [comment]
`noun_s2p` converts singular nouns into their plural form by appending *s* at the end.

`verb_p2s` transforms **verbs** from a form valid for plural nouns into a form suitable for singular nouns, e.g., think 3rd person singular. Since *fly* is a verb:

* "we fly" -- plural, and
* "it flies" -- singular.

**Comment by DWhettam** [comment]
Thanks! I was interpreting _fly_ as:
- "the fly" - singular
- "many flies" - plural

if we are converting from fly (plural), to flies(singular), why is the grammar looking for fly?
```
pred(fly, 1,[v/fly]).
```

**Comment by So-Cool** [comment]
I don't really understand the question. It may be best to ask @flach since he's the author of the code.

**Comment by flach** [comment]
I (arbitrarily) chose the shorter form as the default, so singular for nouns (human→humans) and plural for verbs (walk→walks).
